# 에러처리

에러를 적절히 대처한다면 코드는 강제 종료되지 않는다. 하지만 에러 처리를 제대로 하지 않는다면 코드는 강제 종료된다.

```
// 강제 종료되는 코드
console.log("[Start]");

foo();

// 실행되지 않는다.
console.log("[End]");
```

```
// 강제 종료되는 코드
console.log("[Start]");

try {
    foo();
} catch (e) {
    console.log(e); // foo is not defined
}

// 실행된다.
console.log("[End]");
```

# 에러의 전파

에러는 실행 컨텍스트 스택에서 상위에서 하위로 전파된다.

> 예를 들어 스택에 전역 => baz 함수 => bar 함수 => foo 함수가 있고 foo에서 에러가 발생되면 에러는 foo => bar => baz => 전역으로 전파된다.
